fix ram allocation

diff --git a/usr/bin/ln-vm b/usr/bin/ln-vm
--- a/usr/bin/ln-vm
+++ b/usr/bin/ln-vm
@@ -17,7 +17,7 @@ CDROM=",file=/dev/cdrom"
 FLOPPY=
 # if empty recalculated below 
 RAM=
-CPU=kvm32
+CPU=kvm64
 SMP=
 VGA=qxl
 GUEST_DISABLE=false
@@ -36,7 +36,9 @@ WIN_WIDTH=1024
 WIN_HEIGHT=768
 
 echo $name $master $local
-DSK=$(readlink -f $local | cut -d "/" -f 3)
+DSK=$(readlink -f $local | rev | cut -d "/" -f1 | rev) 
+#DSK=$(readlink -f $local | cut -d "/" -f 3)
+echo $DSK
 
 ####################
 
@@ -243,8 +245,8 @@ function do_sync() {
 
     # custom vms (no ln-vm skel)
     if [ ! -f ${VM_MAIN}/.config ] && [ ! -f ${VM_MAIN}/.setup ]; then
-	rsync -av ${VM_MAIN}/ ${CURRENT}/
-	return 10
+	    rsync -av ${VM_MAIN}/ ${CURRENT}/
+	    return 10
     fi
 
     update_vm_date
@@ -296,9 +298,11 @@ function do_sync() {
 }
 
 function do_rollback() {
+    name=$1
     echo -n "Rollback kvm ..."
-    LAST_SNAP=$(zfs list -t snapshot -o name | grep vm | tail -1)
+    LAST_SNAP=$(zfs list -t snapshot -o name | grep ${name} | tail -1)
     zfs rollback ${LAST_SNAP}
+    
 }
 
 function do_client_call() {
@@ -466,37 +470,38 @@ done
 
 function do_start_kvm() {
     #clean ram
-    ln-client --ram-flush
+    ln-client --ramflush
     #rollback to latest commit
-    do_rollback
+    do_rollback ${name}
     
-    if [ ! -f ${VM_IMG} ]; then
-        echo "ERROR: no ${VM_IMG}"
-        exit 1
-    fi
+    # if [ ! -f ${VM_IMG} ]; then
+    #     echo "ERROR: no ${VM_IMG}"
+    #     exit 1
+    # fi
     
-    if [ -f ${DIRTY_FLAG} ]; then
-        echo "ERROR: dirty ${VM_IMG}"
-        exit 1
-    fi
+    # if [ -f ${DIRTY_FLAG} ]; then
+    #     echo "ERROR: dirty ${VM_IMG}"
+    #     exit 1
+    # fi
 
-    if [ ! -f ${SESSION_IMG} ]; then
-        echo -n "Starting new kvm session ..."
-        qemu-img create -f qed -o cluster_size=8192 -b ${VM_IMG} ${SESSION_IMG} >/dev/null
-        chmod g+w ${SESSION_IMG}
-        echo "OK"
-    else
-        echo "Resume session"
-    fi
+   # if [ ! -f ${SESSION_IMG} ]; then
+   #     echo -n "Starting new kvm session ..."
+   #     qemu-img create -f qed -o cluster_size=8192 -b ${VM_IMG} ${SESSION_IMG} >/dev/null
+   #     chmod g+w ${SESSION_IMG}
+   #     echo "OK"
+   # else
+   #     echo "Resume session"
+   # fi
 
-    # half +1
+    #half +1
+
     [ -n "${SMP}" ] || SMP=$(( 1+$( egrep "^processor" /proc/cpuinfo | wc -l )/2 ))
 
     # calculate half RAM
     if [ -z "${RAM}" ]; then
         RAM=$(( $( sed -n "s|^MemTotal:\s*\([0-9]*\).*$|\1|p"  /proc/meminfo )/1024/2 ))
-        if [ ${RAM} -gt 2047 ]; then
-            RAM=2047
+        if [ ${RAM} -gt 4096 ]; then
+            RAM=4096
         fi
     fi
 
@@ -510,12 +515,14 @@ function do_start_kvm() {
 
     i=1
     KVM_DISKS=""
-    for vm_disk in $(ls ${CURRENT}/vm*.img); do
-        [ -f ${vm_disk} ] || continue
-        KVM_DISKS="${KVM_DISKS} -drive file=${vm_disk},if=none,id=virtio-disk${i},format=raw,cache=writeback,werror=ignore,rerror=ignore -device virtio-blk-pci,scsi=off,drive=virtio-disk${i},id=disk${i}"
-        KVM_DISKS_LOG=" ${vm_disk}"
-        i=$(($i+1))
-    done
+    #find all disks in 
+
+   # for vm_disk in $(ls ${CURRENT}/vm*.img); do
+   #     [ -f ${vm_disk} ] || continue
+   #     KVM_DISKS="${KVM_DISKS} -drive file=${vm_disk},if=none,id=virtio-disk${i},format=raw,cache=writeback,werror=ignore,rerror=ignore -device virtio-blk-pci,scsi=off,drive=virtio-disk${i},id=disk${i}"
+   #     KVM_DISKS_LOG=" ${vm_disk}"
+   #     i=$(($i+1))
+   # done
 
     if [ -f ${CURRENT}/.ich9-ehci-uhci.cfg ]; then
         USB2="-readconfig ${CURRENT}/.ich9-ehci-uhci.cfg"
@@ -536,7 +543,7 @@ function do_start_kvm() {
     fi
     
     # if pulseaudio is running with another user reinitialize it
-    _PULSEUSER=$(ps -C pulseaudio -o user=)
+    _PULSEUSER=$(ps -C pulseaudio -o user= | grep $(whoami) )
     if [ -n "${_PULSEUSER}" ] && [ "${_PULSEUSER}" != "$(whoami)" ]; then
         echo "Restarting pulseaudio"
         sudo killall pulseaudio
@@ -544,10 +551,7 @@ function do_start_kvm() {
     audio_on
 
     echo "Starting kvm with RAM=${RAM}MB, CPU=${SMP}, SOUND=${KVM_SOUND} DISKS='vm.img${KVM_DISKS_LOG}' GUI=${GUI} SHARE=${SHARE}"
-    #ln-network
-    #TODO improve
-    #ln-vm --rollback
-#    HDD=/dev/zvol/zfs-pool/kvm/win10
+
      HDD=/dev/$DSK
 #${KVM_DISKS} \
     kvm \
@@ -557,7 +561,7 @@ function do_start_kvm() {
         -m ${RAM} \
         -cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time \
         -nodefaults -rtc base=localtime \
-        -drive file=$HDD,if=virtio,index=0,cache=none\
+        -drive file=$HDD,if=virtio,index=0,format=raw,cache=writeback,werror=ignore,rerror=ignore\
         -vga ${VGA} \
         -k ${XKBLAYOUT:=it} \
         -monitor tcp:127.0.0.1:4444,server,nowait \
@@ -570,7 +574,7 @@ function do_start_kvm() {
         ${VM_OPTIONS} &
     PID_VM=$!
 
-    check.sh &
+    #check.sh &
     P1=$! 
 #    echo "PID of VM:${PID_VM}"
     if [ -n "${SHARE2}" ] && [ -d ${SHARE2} ]; then
@@ -595,7 +599,7 @@ function do_start_kvm() {
         #( sleep 10 && ( echo "sendkeys ctrl-alt-u" | nc localhost ${MONITOR_PORT} -w1 ) ) &
     fi
 
-    wait ${PID_VM} ${P1}
+    wait ${PID_VM} #${P1}
 
 
 }
